# Change these first
owner: infraestructuraidt # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Sitio WEB Unimonserrate
    url: https://www.unimonserrate.edu.co/
  - name: Biblioteca Digital
    url: https://unimonserrate-library.ohelit.co/
  - name: Revistas y publicaciones
    url: http://revistas.unimonserrate.edu.co:8080/index.php
  - name: CAU / CAE
    url: http://mesadeayuda.unimonserrate.edu.co:8080/
  - name: Praxis
    url: http://virtual.fum.edu.co:9090/Praxis-war/faces/Login.xhtml
  - name: Alpha
    url: http://virtual.fum.edu.co:9090/ProgramacionDocente-war/
  - name: Paz y salvos
    url: http://virtual.fum.edu.co:8081/#/
  - name: Unimonserrate Aulas Virtuales
    url: https://aulasvirtuales.unimonserrate.edu.co

assignees:
  - ohelitco

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: estado.unimonserrate.edu.co
  # baseUrl: /your-repo-name
  logoUrl: https://cpincodemar.edu.co/wp-content/uploads/2021/02/unimonserrate.png
  name: Status IT services
  introTitle: "Estado de servicios de TI Unimonserrate"
  introMessage: En este sitio encuentras la información de estado actual de todos nuestros servicios WEB públicos
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
